### ISSUE TITLE
Exported Transitions Not working.

### ISSUE THREAD

**Issue by Bonkahe** [maktoobgar/scene_manager#2]
So if you export the game with the default code the transitions will not work, as the files within the shader_patterns folder have all had a ".import" file type added.

Here's the code to work around this, but it does require the adding of a build feature called "standalone" to the export.
Line 30: scene_manager.gd

> if not OS.has_feature("standalone"):
> if file_folder.get_extension() == "png":
> _patterns[file_folder.replace("."+file_folder.get_extension(), "")] = load(root_path + file_folder)
> else:
> if file_folder.get_extension() == "import":
> _patterns[file_folder.replace("."+file_folder.get_extension(), "").replace(".png", "")] = load(root_path + file_folder.replace("."+file_folder.get_extension(), ""))

Not sure if this helps any, but I hope it does.

**Comment by maktoobgar** [comment]
Thanks for creating this issue.
Let me see if there is a better way because I really want user to just use this addon and have fun with the tool and do not worry about the additional addon installation and this solution that you provided, complexes addon setup for user just a little bit.
I think I can fix this in another way...

I'll be back and hopefully with some resolving commits.

**Comment by maktoobgar** [comment]
This is now fixed.
no need to setup anything, just use the latest versions:

godot3: https://github.com/maktoobgar/scene_manager/releases/tag/2.2.1
godot4: https://github.com/maktoobgar/scene_manager/releases/tag/3.4.1

**Comment by Bonkahe** [comment]
And that resolved the issue! thank you very much.
