### ISSUE TITLE
Change scene could free other nodes

### ISSUE THREAD

**Issue by JelmerBerghs** [maktoobgar/scene_manager#27]
Do i understand this line of code correctly:
Remove the last node in the root of the tree, being the instanced scene by the scene manager.

https://github.com/maktoobgar/scene_manager/blob/1aefe133cada64f5eb7afa5e2a2dcd6bca994c1b/addons/scene_manager/scene_manager.gd#L153

If i add my own nodes to the end of the tree(for example some data node to persist between scene change), it could free my own node instead of the scene node.

I'm wondering why you dont simply call free on the 'current_scene'. 

Im not sure if i'm understanding the code correctly, i'd love to learn why it was implemented this way.

**Comment by maktoobgar** [comment]
Hi,
I can't defend that line of code, It was what I thought was right at the moment and if you add another node after the current node, it would delete your node instead of the current scene itself.
It is a problem, you are right.
I'll fix it in future version, it seems like there's gonna be a lot of bug fixing in the next version.
Thanks for taking your time to create an issue.
