### ISSUE TITLE
Deprecated parameter names in scene_manager.gdshader

### ISSUE THREAD

**Issue by MashedD** [maktoobgar/scene_manager#5]
scene_manager: master branch (3.4.1)
Godot: v4.0.rc6.official [0cd148313]
OS: Windows 10

After starting a simple demo app after pressing F5 I get a lot of warnings:

_set: This material (containing shader with path: 'res://addons/scene_manager/scene_manager.gdshader') uses an old deprecated parameter names. Consider re-saving this resource (or scene which contains it) in order for it to continue working in future versions.

**Comment by MashedD** [comment]
I've found: https://github.com/godotengine/godot/issues/72575 and your question on Stackoverflow :)
The solution is to open scene_manager.tscn, double click on animation_player and replace in all four animations "shader_param" to "shader_parameter".

Solution is based on two info-s:
- https://github.com/godotengine/godot/blob/master/scene/resources/material.cpp#L177
- warnings were displayed when opening a scene, so when animation was player

I hope this will solve a problem for you as well :)

**Comment by maktoobgar** [comment]
@MashedD
Thank you so much, that actually fixed the problem but at least consider answering the question with your account in stackoverflow so that I could assign your answer as accepted answer for just the reputation of answering the question.
That's nothing but that's what I can offer at the time plus you can make a pull request for this problem too if you want to get the credibility for it and be considered as a contributor in this little repository.

Thanks again. ❤️

**Comment by MashedD** [comment]
No problem :) I don't have an account on SO, so you can write an answer there or link to this thread. I'll try to prepare a Pull Request later today.
